version: '3'
services:
  worker:
    image: onetwotrip-test-1-worker:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  worker-get-errors:
    image: onetwotrip-test-1-worker:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    command: --getErrors

  worker-requeue:
    image: onetwotrip-test-1-worker:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    command: --requeue

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - '63799:6379'